# Конфигурация модуля физики
settings:
  block-falling: false        # Включение/выключение падения блоков (например, песок, гравий)
  plant-growth: false         # Включение/выключение роста растений
  liquid-flow: false          # Включение/выключение течения жидкостей (вода, лава)
  block-spread: false         # Включение/выключение распространения блоков (например, трава, огонь)
  leaf-decay: false           # Включение/выключение опадания листвы
  coral-dry: false            # Включение/выключение высыхания кораллов
  snow-melt: false            # Включение/выключение таяния снега
  block-break-support: false  # Включение/выключение разрушения поддерживаемых блоков (лестницы, рельсы и т.д.)
  concrete-hardening: false # Включение/выключение вымачивания бетона